[project]
name = "spider_silkome"
description = "Spider Silkome"
version = "0.1.0"
channels = ['conda-forge','bioconda']
platforms = ['linux-64']

[dependencies]
python = "~=3.10.0"
ipython = "*"
jupyterlab = "*"
loguru = "*"
matplotlib = "*"
notebook = "*"
numpy = "*"
pandas = ">=2.3.3,<3"
pytest = "*"
ruff = "*"
scikit-learn = "*"
tqdm = "*"
typer = "*"
pip = "*"
miniprot = "0.18.*"
csvtk = ">=0.34.0,<0.35"
biopython = ">=1.85,<2"

[pypi-dependencies]
mkdocs = "*"
python-dotenv = "*"
spider_silkome_module = { path = ".", editable = true }
